# Generated by Django 4.1.1 on 2022-11-08 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_keras_facenet_probability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keras_facenet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
